## Importação das Bibliotecas

In [1]:
import requests
import pandas as pd
import json

## COLETA DA API REST

In [2]:
#criação de uma variável para armazenar a url que contém os dados da API
#Uso da biblioteca requests com o método GET para obter os dados da API

url = r'http://127.0.0.1:5000/country'
r = requests.get(url)
print(r.status_code)                            #exibe o status da requisição feita para a API para verificar se foi realizada com sucesso ('CÓDIGO: 200' indica que deu certo)
print(r.json())                                 #exibe o conteúdo da API em formato json

200

In [3]:
#Criação de um DataFrame com os dados obtidos da API
#Uso do 'orient=index' devido ao json possuir a estrutura com índices
#transformação do índice, que se refere aos código dos países, em uma coluna no DataFrame com a nomenclatura 'code'


df_api_original = pd.DataFrame.from_dict(dict(r.json()), orient='index').reset_index().rename(columns={'index':'code'})
df_api = df_api_original.copy()   #criação de uma cópia do DataFrame para manipulação dos dados e presevação do original

In [4]:
#exibição do DataFrame para melhor visualização dos dados obtidos com a API

df_api

,code,name,currency,population,capital,continent,area
0,AND,Andorra,EUR,77006,Andorra la Vella,Europe,468.0
1,ARE,United Arab Emirates,AED,9630959,Abu Dhabi,Asia,82880.0
2,AFG,Afghanistan,AFN,37172386,Kabul,Asia,647500.0
3,ATG,Antigua and Barbuda,XCD,96286,St John's,North America,443.0
4,AIA,Anguilla,XCD,13254,The Valley,North America,102.0
...,...,...,...,...,...,...,...
245,YEM,Yemen,YER,28498687,Sanaa,Asia,527970.0
246,MYT,Mayotte,EUR,279471,Mamoudzou,Africa,374.0
247,ZAF,South Africa,ZAR,57779622,Pretoria,Africa,1219912.0
248,ZMB,Zambia,ZMW,17351822,Lusaka,Africa,752614.0
249,ZWE,Zimbabwe,ZWL,14439018,Harare,Africa,390580.0

In [5]:
#Verificação do tipo de dado de cada coluna e da quantidade de valores não nulos

df_api.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        250 non-null    object
 1   name        250 non-null    object
 2   currency    250 non-null    object
 3   population  250 non-null    int64
 4   capital     250 non-null    object
 5   continent   250 non-null    object
 6   area        250 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 13.8+ KB

## COLETA DO ARQUIVO CSV

In [6]:
#Leitura do arquivo CSV que contém os dados do PIB e criação de um DataFrame com os dados

df_arq_original = pd.read_csv('gdp_data.csv')
df_arq = df_arq_original.copy()                         #criação de uma cópia do DataFrame para manipulação dos dados e presevação do original

In [7]:
#exibição do DataFrame para melhor visualização dos dados

df_arq

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129081e+10,2.180870e+10,2.370727e+10,2.821034e+10,2.611906e+10,2.968249e+10,...,9.834729e+11,1.003768e+12,9.245228e+11,8.827213e+11,1.021119e+12,1.007240e+12,1.001017e+12,9.274845e+11,1.080712e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,...,8.322169e+11,8.924979e+11,7.669580e+11,6.905454e+11,6.837480e+11,7.663597e+11,7.947191e+11,7.847997e+11,8.401873e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.361907e+10,6.740429e+10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.041597e+11,3.885320e+11,3.376197e+11,4.190150e+11,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10,NaN

In [8]:
#Verificação do tipo de dado de cada coluna e da quantidade de valores não nulos

df_arq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 67 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            133 non-null    float64
 5   1961            135 non-null    float64
 6   1962            137 non-null    float64
 7   1963            137 non-null    float64
 8   1964            137 non-null    float64
 9   1965            148 non-null    float64
 10  1966            151 non-null    float64
 11  1967            155 non-null    float64
 12  1968            160 non-null    float64
 13  1969            160 non-null    float64
 14  1970            169 non-null    float64
 15  1971            172 non-null    float64
 16  1972            172 non-null    float64
 17  1973            172 non-null    float64
 18  1974            173 non-null    float64
 19  1975            175 non-null    float64
 20  1976            176 non-null    float64
 21  1977            179 non-null    float64
 22  1978            178 non-null    float64
 23  1979            179 non-null    float64
 24  1980            191 non-null    float64
 25  1981            194 non-null    float64
 26  1982            195 non-null    float64
 27  1983            196 non-null    float64
 28  1984            197 non-null    float64
 29  1985            199 non-null    float64
 30  1986            201 non-null    float64
 31  1987            205 non-null    float64
 32  1988            210 non-null    float64
 33  1989            210 non-null    float64
 34  1990            226 non-null    float64
 35  1991            226 non-null    float64
 36  1992            227 non-null    float64
 37  1993            229 non-null    float64
 38  1994            231 non-null    float64
 39  1995            240 non-null    float64
 40  1996            240 non-null    float64
 41  1997            240 non-null    float64
 42  1998            242 non-null    float64
 43  1999            243 non-null    float64
 44  2000            247 non-null    float64
 45  2001            249 non-null    float64
 46  2002            254 non-null    float64
 47  2003            254 non-null    float64
 48  2004            254 non-null    float64
 49  2005            254 non-null    float64
 50  2006            255 non-null    float64
 51  2007            255 non-null    float64
 52  2008            256 non-null    float64
 53  2009            256 non-null    float64
 54  2010            257 non-null    float64
 55  2011            260 non-null    float64
 56  2012            258 non-null    float64
 57  2013            259 non-null    float64
 58  2014            260 non-null    float64
 59  2015            258 non-null    float64
 60  2016            257 non-null    float64
 61  2017            257 non-null    float64
 62  2018            257 non-null    float64
 63  2019            255 non-null    float64
 64  2020            252 non-null    float64
 65  2021            245 non-null    float64
 66  Unnamed: 66     0 non-null      float64
dtypes: float64(63), object(4)
memory usage: 139.4+ KB

In [9]:
#remoção das colunas que não serão utilizadas.

colunas_remover = ['Indicator Name','Indicator Code','Unnamed: 66']
df_arq = df_arq.drop(columns=colunas_remover)
df_arq                              #exibição do DataFrame após a remoção das coluna para verificar se ficou correto

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09
1,Africa Eastern and Southern,AFE,2.129081e+10,2.180870e+10,2.370727e+10,2.821034e+10,2.611906e+10,2.968249e+10,3.223946e+10,3.351491e+10,...,9.725734e+11,9.834729e+11,1.003768e+12,9.245228e+11,8.827213e+11,1.021119e+12,1.007240e+12,1.001017e+12,9.274845e+11,1.080712e+12
2,Afghanistan,AFG,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
3,Africa Western and Central,AFW,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,1.583259e+10,1.442604e+10,...,7.360399e+11,8.322169e+11,8.924979e+11,7.669580e+11,6.905454e+11,6.837480e+11,7.663597e+11,7.947191e+11,7.847997e+11,8.401873e+11
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249982e+11,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.361907e+10,6.740429e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09
262,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540132e+10,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN
263,South Africa,ZAF,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.041597e+11,3.885320e+11,3.376197e+11,4.190150e+11
264,Zambia,ZMB,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10
265,Zimbabwe,ZWE,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10

## CONSOLIDAÇÃO DOS DADOS (API REST + CSV)

In [10]:
#junção do DataFrame com os dados da API REST e do DataFrame com os dados do CSV em um único DataFrame, com uso da função 'merge'
#uso do parâmetro 'how=left' que pega todos os valores do DataFrame com os dados da API e junta com o DataFrame com os dados do CSV.
#junção realizada a partir da coluna 'code' que pertence ao df_api e da coluna 'Country Code' que pertencem ao df_arq, que representam o código do país (coluna em comum entre os DataFrames)
#registros que constam no CSV, mas não constam na API são desconsiderados 



df_unificado = pd.merge(df_api,df_arq, how = 'left', left_on='code', right_on='Country Code')
df_unificado                             #exibição do DataFrame após a junção para verificar se ficou correto

,code,name,currency,population,capital,continent,area,Country Name,Country Code,1960,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AND,Andorra,EUR,77006,Andorra la Vella,Europe,468.0,Andorra,AND,NaN,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
1,ARE,United Arab Emirates,AED,9630959,Abu Dhabi,Asia,82880.0,United Arab Emirates,ARE,NaN,...,3.846101e+11,4.002185e+11,4.141054e+11,3.702755e+11,3.692553e+11,3.905168e+11,4.270494e+11,4.179897e+11,3.494730e+11,4.150216e+11
2,AFG,Afghanistan,AFN,37172386,Kabul,Asia,647500.0,Afghanistan,AFG,5.377778e+08,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
3,ATG,Antigua and Barbuda,XCD,96286,St John's,North America,443.0,Antigua and Barbuda,ATG,NaN,...,1.199948e+09,1.181448e+09,1.249733e+09,1.336693e+09,1.436585e+09,1.467978e+09,1.605944e+09,1.687533e+09,1.370281e+09,1.471126e+09
4,AIA,Anguilla,XCD,13254,The Valley,North America,102.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,YEM,Yemen,YER,28498687,Sanaa,Asia,527970.0,"Yemen, Rep.",YEM,NaN,...,3.540132e+10,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN
246,MYT,Mayotte,EUR,279471,Mamoudzou,Africa,374.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,ZAF,South Africa,ZAR,57779622,Pretoria,Africa,1219912.0,South Africa,ZAF,8.748597e+09,...,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.041597e+11,3.885320e+11,3.376197e+11,4.190150e+11
248,ZMB,Zambia,ZMW,17351822,Lusaka,Africa,752614.0,Zambia,ZMB,7.130000e+08,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10
249,ZWE,Zimbabwe,ZWL,14439018,Harare,Africa,390580.0,Zimbabwe,ZWE,1.052990e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10

In [11]:
#Verificação da quantidade de valores não nulos
df_unificado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 71 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   code          250 non-null    object
 1   name          250 non-null    object
 2   currency      250 non-null    object
 3   population    250 non-null    int64
 4   capital       250 non-null    object
 5   continent     250 non-null    object
 6   area          250 non-null    float64
 7   Country Name  216 non-null    object
 8   Country Code  216 non-null    object
 9   1960          100 non-null    float64
 10  1961          102 non-null    float64
 11  1962          104 non-null    float64
 12  1963          104 non-null    float64
 13  1964          104 non-null    float64
 14  1965          113 non-null    float64
 15  1966          115 non-null    float64
 16  1967          118 non-null    float64
 17  1968          120 non-null    float64
 18  1969          120 non-null    float64
 19  1970          126 non-null    float64
 20  1971          128 non-null    float64
 21  1972          128 non-null    float64
 22  1973          128 non-null    float64
 23  1974          129 non-null    float64
 24  1975          131 non-null    float64
 25  1976          132 non-null    float64
 26  1977          135 non-null    float64
 27  1978          134 non-null    float64
 28  1979          135 non-null    float64
 29  1980          146 non-null    float64
 30  1981          149 non-null    float64
 31  1982          150 non-null    float64
 32  1983          151 non-null    float64
 33  1984          152 non-null    float64
 34  1985          154 non-null    float64
 35  1986          156 non-null    float64
 36  1987          160 non-null    float64
 37  1988          163 non-null    float64
 38  1989          163 non-null    float64
 39  1990          178 non-null    float64
 40  1991          178 non-null    float64
 41  1992          179 non-null    float64
 42  1993          181 non-null    float64
 43  1994          183 non-null    float64
 44  1995          192 non-null    float64
 45  1996          192 non-null    float64
 46  1997          192 non-null    float64
 47  1998          193 non-null    float64
 48  1999          194 non-null    float64
 49  2000          198 non-null    float64
 50  2001          200 non-null    float64
 51  2002          205 non-null    float64
 52  2003          205 non-null    float64
 53  2004          205 non-null    float64
 54  2005          205 non-null    float64
 55  2006          206 non-null    float64
 56  2007          206 non-null    float64
 57  2008          208 non-null    float64
 58  2009          208 non-null    float64
 59  2010          209 non-null    float64
 60  2011          212 non-null    float64
 61  2012          210 non-null    float64
 62  2013          211 non-null    float64
 63  2014          212 non-null    float64
 64  2015          210 non-null    float64
 65  2016          209 non-null    float64
 66  2017          209 non-null    float64
 67  2018          209 non-null    float64
 68  2019          207 non-null    float64
 69  2020          204 non-null    float64
 70  2021          197 non-null    float64
dtypes: float64(63), int64(1), object(7)
memory usage: 138.8+ KB

In [12]:
#verificação das colunas que possuem valores ausentes

df_unificado.isna()

,code,name,currency,population,capital,continent,area,Country Name,Country Code,1960,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,True,True
246,False,False,False,False,False,False,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
247,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
248,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
#verificação da quantidade de valores ausentes na coluna 'Country Name' que pertence ao dados extraídos do CSV
#a partir dessa consulta foi possível confirmar que há registros que constam apenas na API, visto que foram identificados valores ausentes na coluna 'Country Name' que pertence aos dados coletados do CSV

df_unificado['Country Name'].isna().sum()

np.int64(34)

In [14]:
#verificação da quantidade de valores ausentes na coluna 'Country Code' que pertence ao dados extraídos do CSV
#a partir dessa consulta foi possível confirmar que há registros que constam apenas na API, visto que foram identificados valores ausentes na coluna 'Country Code' que pertence aos dados coletados do CSV

df_unificado['Country Code'].isna().sum()

np.int64(34)

In [15]:
#remoção das linhas que possuem valores ausentes nas colunas 'Country Name' e 'Country Code'

df_unificado = df_unificado.dropna(subset=['Country Name','Country Code'])
df_unificado

,code,name,currency,population,capital,continent,area,Country Name,Country Code,1960,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AND,Andorra,EUR,77006,Andorra la Vella,Europe,468.0,Andorra,AND,NaN,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
1,ARE,United Arab Emirates,AED,9630959,Abu Dhabi,Asia,82880.0,United Arab Emirates,ARE,NaN,...,3.846101e+11,4.002185e+11,4.141054e+11,3.702755e+11,3.692553e+11,3.905168e+11,4.270494e+11,4.179897e+11,3.494730e+11,4.150216e+11
2,AFG,Afghanistan,AFN,37172386,Kabul,Asia,647500.0,Afghanistan,AFG,5.377778e+08,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
3,ATG,Antigua and Barbuda,XCD,96286,St John's,North America,443.0,Antigua and Barbuda,ATG,NaN,...,1.199948e+09,1.181448e+09,1.249733e+09,1.336693e+09,1.436585e+09,1.467978e+09,1.605944e+09,1.687533e+09,1.370281e+09,1.471126e+09
5,ALB,Albania,ALL,2866376,Tirana,Europe,28748.0,Albania,ALB,NaN,...,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.825579e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,XKX,Kosovo,EUR,1845300,Pristina,Europe,10908.0,Kosovo,XKX,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09
245,YEM,Yemen,YER,28498687,Sanaa,Asia,527970.0,"Yemen, Rep.",YEM,NaN,...,3.540132e+10,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN
247,ZAF,South Africa,ZAR,57779622,Pretoria,Africa,1219912.0,South Africa,ZAF,8.748597e+09,...,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.041597e+11,3.885320e+11,3.376197e+11,4.190150e+11
248,ZMB,Zambia,ZMW,17351822,Lusaka,Africa,752614.0,Zambia,ZMB,7.130000e+08,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10
249,ZWE,Zimbabwe,ZWL,14439018,Harare,Africa,390580.0,Zimbabwe,ZWE,1.052990e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10

In [16]:
#remoção da coluna 'Country Code' e 'Country Name', pois as colunas 'code' e 'name' possuem as mesmas informações

colunas_remover_unificado = ['Country Code','Country Name']
df_unificado = df_unificado.drop(columns=colunas_remover_unificado)
df_unificado

,code,name,currency,population,capital,continent,area,1960,1961,1962,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AND,Andorra,EUR,77006,Andorra la Vella,Europe,468.0,NaN,NaN,NaN,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
1,ARE,United Arab Emirates,AED,9630959,Abu Dhabi,Asia,82880.0,NaN,NaN,NaN,...,3.846101e+11,4.002185e+11,4.141054e+11,3.702755e+11,3.692553e+11,3.905168e+11,4.270494e+11,4.179897e+11,3.494730e+11,4.150216e+11
2,AFG,Afghanistan,AFN,37172386,Kabul,Asia,647500.0,5.377778e+08,5.488889e+08,5.466667e+08,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
3,ATG,Antigua and Barbuda,XCD,96286,St John's,North America,443.0,NaN,NaN,NaN,...,1.199948e+09,1.181448e+09,1.249733e+09,1.336693e+09,1.436585e+09,1.467978e+09,1.605944e+09,1.687533e+09,1.370281e+09,1.471126e+09
5,ALB,Albania,ALL,2866376,Tirana,Europe,28748.0,NaN,NaN,NaN,...,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.825579e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,XKX,Kosovo,EUR,1845300,Pristina,Europe,10908.0,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09
245,YEM,Yemen,YER,28498687,Sanaa,Asia,527970.0,NaN,NaN,NaN,...,3.540132e+10,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN
247,ZAF,South Africa,ZAR,57779622,Pretoria,Africa,1219912.0,8.748597e+09,9.225996e+09,9.813996e+09,...,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.041597e+11,3.885320e+11,3.376197e+11,4.190150e+11
248,ZMB,Zambia,ZMW,17351822,Lusaka,Africa,752614.0,7.130000e+08,6.962857e+08,6.931429e+08,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10
249,ZWE,Zimbabwe,ZWL,14439018,Harare,Africa,390580.0,1.052990e+09,1.096647e+09,1.117602e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10

In [17]:
#Verificação da quantidade de valores não nulos após a unificação e ajustes do DataFrame

df_unificado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 216 entries, 0 to 249
Data columns (total 69 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        216 non-null    object
 1   name        216 non-null    object
 2   currency    216 non-null    object
 3   population  216 non-null    int64
 4   capital     216 non-null    object
 5   continent   216 non-null    object
 6   area        216 non-null    float64
 7   1960        100 non-null    float64
 8   1961        102 non-null    float64
 9   1962        104 non-null    float64
 10  1963        104 non-null    float64
 11  1964        104 non-null    float64
 12  1965        113 non-null    float64
 13  1966        115 non-null    float64
 14  1967        118 non-null    float64
 15  1968        120 non-null    float64
 16  1969        120 non-null    float64
 17  1970        126 non-null    float64
 18  1971        128 non-null    float64
 19  1972        128 non-null    float64
 20  1973        128 non-null    float64
 21  1974        129 non-null    float64
 22  1975        131 non-null    float64
 23  1976        132 non-null    float64
 24  1977        135 non-null    float64
 25  1978        134 non-null    float64
 26  1979        135 non-null    float64
 27  1980        146 non-null    float64
 28  1981        149 non-null    float64
 29  1982        150 non-null    float64
 30  1983        151 non-null    float64
 31  1984        152 non-null    float64
 32  1985        154 non-null    float64
 33  1986        156 non-null    float64
 34  1987        160 non-null    float64
 35  1988        163 non-null    float64
 36  1989        163 non-null    float64
 37  1990        178 non-null    float64
 38  1991        178 non-null    float64
 39  1992        179 non-null    float64
 40  1993        181 non-null    float64
 41  1994        183 non-null    float64
 42  1995        192 non-null    float64
 43  1996        192 non-null    float64
 44  1997        192 non-null    float64
 45  1998        193 non-null    float64
 46  1999        194 non-null    float64
 47  2000        198 non-null    float64
 48  2001        200 non-null    float64
 49  2002        205 non-null    float64
 50  2003        205 non-null    float64
 51  2004        205 non-null    float64
 52  2005        205 non-null    float64
 53  2006        206 non-null    float64
 54  2007        206 non-null    float64
 55  2008        208 non-null    float64
 56  2009        208 non-null    float64
 57  2010        209 non-null    float64
 58  2011        212 non-null    float64
 59  2012        210 non-null    float64
 60  2013        211 non-null    float64
 61  2014        212 non-null    float64
 62  2015        210 non-null    float64
 63  2016        209 non-null    float64
 64  2017        209 non-null    float64
 65  2018        209 non-null    float64
 66  2019        207 non-null    float64
 67  2020        204 non-null    float64
 68  2021        197 non-null    float64
dtypes: float64(63), int64(1), object(5)
memory usage: 118.1+ KB

In [18]:
#Criação de um arquivo CSV gerado a partir do DataFrame unificado que possui todas as informações dos países

df_unificado.to_csv('base_unificada.csv', index=False, encoding='utf-8')